### ISSUE TITLE
Preserve heredocs

### ISSUE THREAD

**Issue by cschneid** [lpil/exfmt#11]
See the moduledoc at the top of: https://gist.github.com/cschneid/5eb14df36143b6080db5bbb9fee697b5

The triple-quoted string is transformed into a single-quoted string with \n and escapes.

```
@moduledoc "Singleton that manages the state of the Agent's data.  Mostly just\nroutes data to the correct per-minute data structure\n\nAlso is the core \"tick\" of the system, so each X seconds, the data\ncollected is checked to see if it's ready to be reported. If so, the\nreporting process is kicked off.\n"
```

(this issue is spawned from #10)

**Comment by lpil** [comment]
We should certainly render strings as heredocs when suitable, though I'm unsure when we should do this.

### Option 1

Render strings as heredocs when the string contains a newline `\n`.

### Option 2

Render strings as heredocs when they are written as heredocs. This would require forking the Elixir yecc parser as it discards this information. It's unlikely that this modification would get merged back into the Elixir project.

**Comment by kumekay** [comment]
In general I like option 1.
Do you see any problems with it?

**Comment by lpil** [comment]
Not really, could do the trick :)

**Comment by lpil** [comment]
Elixir's master branch now has the ability to retain this information during parsing, so we can go with option number 2, preservation of heredocs! :)
