### ISSUE TITLE
Prevent fn arrow -> should always be on the same line as fn args

### ISSUE THREAD

**Issue by cschneid** [lpil/exfmt#13]
Function arrows seem somewhat randomly placed. 

one with a [missing space before](https://gist.github.com/cschneid/5eb14df36143b6080db5bbb9fee697b5#file-formatted_store-ex-L121)

one with a [whole line to itself](https://gist.github.com/cschneid/5eb14df36143b6080db5bbb9fee697b5#file-formatted_store-ex-L142)

Spawned from #10

**Comment by lpil** [comment]
I believe I may have just fixed this with dada9f0db2fe60cbc77e9bfc43854187d059ca2f. Could you try from the master branch please? :)

**Comment by lpil** [comment]
Thank you

**Comment by jfornoff** [comment]
Not ready to be closed, the spacing around 0-arity function arrows is OK now, but the arrows are still broken into the next lines or parts of the body are put after it.

**Comment by lpil** [comment]
Thank you :)
