### ISSUE TITLE
Module Attributes are condensed with next comment & function

### ISSUE THREAD

**Issue by cschneid** [lpil/exfmt#14]
Similar issue to #12 

The "module constant" is smushed down to the comment and function name below it.

### raw

```
  # 60 seconds
  # @tick_interval 60_000
  @tick_interval 10_000

  ## Client API

  def start_link do
    GenServer.start_link(__MODULE__, :ok, [name: __MODULE__])
  end

```

### formatted
```
  # 60 seconds
  # @tick_interval 60_000
  @tick_interval 10000
  ## Client API
  def start_link do
    GenServer.start_link __MODULE__, :ok, name: __MODULE__
  end
```

**Comment by lpil** [comment]
What do you think the expected output should be?

How would you describe the rule? Bare in mind that there are module attributes in Elixir core such as `@doc`, `@spec`, `@tag` and spec that are expected to sit on the line above the def.

Other similar module attributes are used in libraries and tools on hex.pm (such as Credo) too.

Perhaps we could insert a space between a module attribute followed by a comment.

**Comment by cschneid** [comment]
I was thinking that it's hard to do this in a general way.

Types that I see:

* known elixir attributes that "attach" to a function (`@doc`, `@spec`)
* known elixir attributes that don't attach (`@type`, `@opaque`, `@before_compile` and such)
* application-specific module attributes that "attach" to a function tightly ([from your code](https://github.com/lpil/exfmt/blob/master/lib/exfmt.ex#L132)) 
* module-wide "constants" (like what I have above, or more complex ones like this [from your code](https://github.com/lpil/exfmt/blob/master/lib/exfmt/ast.ex#L8))

I imagine you can have specific rules for those first 2.  But I'm not sure a generalized rule for the ones that people come up with themselves.

**Comment by lpil** [comment]
New thought- we could use the line numbers in AST node metadata to detect when a user has deliberately left blank spaces. Blank spaces could then be preserved.
