### ISSUE TITLE
Preserve char lists

### ISSUE THREAD

**Issue by kumekay** [lpil/exfmt#17]
Single-quoted strings formatted as list of ints. It's not compact and readable. It should be better to format lists with printable characters like single quoted strings or leave lists as they were initially.

Now `'test'` is converted to `[116, 101, 115, 116]`.

**Comment by lpil** [comment]
The Elixir compiler's parser doesn't offer a way to differentiate between char lists and lists of integers, so some work would need to be done here.

Given single quoted char lists [are going to be deprecated](https://groups.google.com/forum/#!topic/elixir-lang-core/_pAjPEayLLI) in favour of the less cryptic `~c[]` sigil this isn't high up my to-do list. For now I would recommend switching to using the sigil.

**Comment by kumekay** [comment]
`~c()` looks like good solution for new projects. Thank you
