### ISSUE TITLE
Is it like Prettier(JavaScript/Typescript) for Elixir?

### ISSUE THREAD

**Issue by collegeimprovements** [lpil/exfmt#19]

**Comment by lpil** [comment]
Yes, exactly like that :)

**Comment by collegeimprovements** [comment]
Is there extension(vs-code, vim, emacs) for exfmt available?

**Comment by lpil** [comment]
Work on editor integration had not yet started as the are several bugs that result in incorrect coffee being generated. Once these are fixed work on style and tooling will begin.
