### ISSUE TITLE
Comments put in wrong position

### ISSUE THREAD

**Issue by shdblowers** [lpil/exfmt#20]
Hi @lpil this is a very interesting project, definitely very useful once its finished.

Decided to try it out and found an issue with the first file I gave it, see below:

When I give `exfmt` this:

```elixir
defmodule Mssqlex.Mixfile do
  use Mix.Project

  def project do
    [app: :mssqlex,
     version: "0.7.0",
     description: "Adapter to Microsoft SQL Server. Using DBConnection and ODBC.",
     elixir: ">= 1.4.0",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps(),
     package: package(),
     aliases: aliases(),

     # Testing
     test_coverage: [tool: ExCoveralls],
     preferred_cli_env: ["test.local": :test,
                         "coveralls": :test,
                         "coveralls.travis": :test],

     # Docs
     name: "Mssqlex",
     source_url: "https://github.com/findmypast-oss/mssqlex",
     docs: [main: "readme",
            extras: ["README.md"]]]
  end

  def application do
    [extra_applications: [:logger, :odbc]]
  end

  ...

end
```

I get this:

```elixir
defmodule Mssqlex.Mixfile do
  use Mix.Project

  def project do
    [app: :mssqlex,
     version: "0.7.0",
     description: "Adapter to Microsoft SQL Server. Using DBConnection and ODBC.",
     elixir: ">= 1.4.0",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps(),
     package: package(),
     aliases: aliases(),
     test_coverage: [tool: # Testing
      ExCoveralls],
     preferred_cli_env: ["test.local": :test, coveralls: :test, "coveralls.travis": :test],
     name: "Mssqlex",
     source_url: "https://github.com/findmypast-oss/mssqlex",
     docs: [main: "readme", extras: ["README.md"]]]
  end


  # Docs
  def application do
    [extra_applications: [:logger, :odbc]]
  end

  ...

end
```

Notice where the comments `# Testing` and `# Docs` have been moved to.

**Comment by lpil** [comment]
Hey! Thanks for the report. :)

Currently the comment positioning is limited but the amount of information that the Elixir parser gives us about literal AST nodes. @uohzxela has done some fantastic work that will land in Elixir v1.5 and make more accurate comment rendering possible.

Until then I'm focusing on the semantic correctness of the formatter. Currently if you run the formatter on the v1.4 Elixir compiler code base there are around 50 files that produce crashes or semantically incorrect code. Once these are fixed, v1.5 is out, and some work has been done resolving some of the technical debt in the algebra generation I will focus on the output style :)

**Comment by lpil** [comment]
\+ hey, FindMyPast, cool company! I know some of your colleges from various meetups and events :)

**Comment by shdblowers** [comment]
Sounds like there's so much to do! Haha.

I found the gofmt tool really useful when I tried out Go, so having a similar tool for Elixir would be awesome. I'll play about with it some more and see if I can help in any way.

Yeah, Findmypast are trying to have more of a presence in the Elixir community and give something back. I  saw your talk at Elixir LDN (was really impressed) and there'll be more people going from Findmypast this year.

**Comment by lpil** [comment]
Yes, lots of work! Quite a fiddly project this one and I'm learning as I go so it's quite messy at the moment. I'm confident that the overall design is good though.

Excellent. I'm going to be speaking this year about this project of you're going again. :)

**Comment by lpil** [comment]
Er, I'll be giving the talk if you're not going as well ;)

**Comment by shdblowers** [comment]
I hope that I am going, regardless I'll watch the talk when it goes up on YouTube. :smile:

**Comment by lpil** [comment]
Alas, it seems the required changes are in 1.6, not 1.5. Going to be a bit of a wait.

**Comment by shdblowers** [comment]
👋
