### ISSUE TITLE
Code grouping on functions with multiple bodies

### ISSUE THREAD

**Issue by brunogirin** [lpil/exfmt#22]
When it finds a function declaration, the output format ensures there's white space around it and it expands `,do: ...` constructs into `do ... end`. This is fine to ensure there is white space between functions. However, when a function has several bodies that use pattern matching to choose the correct implementation, it would be useful to ensure that those different bodies are grouped together to indicate that they are parts of the same function.

### Several bodies of equivalent complexity

```elixir
  def etag(data) when is_bitstring(data) or is_binary(data) do
    Crypto.hash(:sha256, data) |> Base.encode64
  end
  def etag(data) do
    Crypto.hash(:sha256, Poison.encode!(data)) |> Base.encode64
  end
```

In this example, I have no space between the two definitions because both define the `etag` function with different conditions on the attributes. Those two blocks belong together. Separating them as if they implemented different functions renders the code less readable.

### First body for trivial or `nil` case, main body below

```elixir
  def key(nil), do: nil
  def key(%Guide{key: key}) do
    something more complicated
  end
```

In this example, the first definition deals with a trivial case to catch a possible `nil` while the meat of the function is in the second definition. Separating them would make it less obvious that the `nil` case is dealt with.

### Implementations where most of the work is done in pattern matching

```elixir
  def handle_result({:atomic, []}, _spec, {:one, _}), do: {:ok, nil}
  def handle_result({:atomic, [r]}, spec, {:one, fmt}), do: {:ok, format_record(r, spec, fmt)}
  def handle_result({:atomic, l}, _spec, {:one, _}), do: {:error, {:too_may, Enum.count(l)}}
  def handle_result({:atomic, l}, spec, {:many, fmt}), do: {:ok, Enum.map(l, &(format_record(&1, spec, fmt)))}
  def handle_result({:atomic, _}, _spec, {:static, v}), do: {:ok, v}
  def handle_result({:atomic, r}, _spec, _mode), do: {:ok, r}
  def handle_result({:aborted, error}, _spec, _mode), do: {:error, error}
  def handle_result(error, _spec, _mode), do: {:error, error}
```

In this case, most of the work is done by the pattern matching, the bodies are (mostly) trivial so the benefit of this presentation is that it clearly shows the different patterns against each other. That said, I end up with individual lines that are slightly too long so maybe a better presentation for this code would be to expand the non-trivial bodies:

```elixir
  def handle_result({:atomic, []}, _spec, {:one, _}), do: {:ok, nil}
  def handle_result({:atomic, [r]}, spec, {:one, fmt}) do
    {:ok, format_record(r, spec, fmt)}
  end
  def handle_result({:atomic, l}, _spec, {:one, _}) do
    {:error, {:too_may, Enum.count(l)}}
  end
  def handle_result({:atomic, l}, spec, {:many, fmt}) do
    {:ok, Enum.map(l, &(format_record(&1, spec, fmt)))}
  end
  def handle_result({:atomic, _}, _spec, {:static, v}), do: {:ok, v}
  def handle_result({:atomic, r}, _spec, _mode), do: {:ok, r}
  def handle_result({:aborted, error}, _spec, _mode), do: {:error, error}
  def handle_result(error, _spec, _mode), do: {:error, error}
```

## Suggestions

* Have different spacing between genuinely different functions than between different bodies of the same function so that the grouping is clear.
* Only expand the `,do: ...` construct into `do ... end` if the full line is longer than 80 characters.

**Comment by lpil** [comment]
> Have different spacing between genuinely different functions than between different bodies of the same function so that the grouping is clear.

This is the current behavior. :)

> Only expand the ,do: ... construct into do ... end if the full line is longer than 80 characters.

Some form of sugarless do block preservation may be implemented at a later date, but not any time soon I'm afraid.

**Comment by lpil** [comment]
Going to close this, please open a new issue for any additions you'd like to request :)
