### ISSUE TITLE
Documentation for Vim integration through sbdchd/neoformat

### ISSUE THREAD

**Issue by lpil** [lpil/exfmt#26]
The Neoformat project allows Vim used to set up formatters quickly and easily.

https://github.com/sbdchd/neoformat/

Let's have some docs on how to do this :)

## Dependencies:

- [x] https://github.com/lpil/exfmt/issues/23
- [x] https://github.com/lpil/exfmt/issues/24
- [x] https://github.com/lpil/exfmt/issues/25

**Comment by jfornoff** [comment]
Will try to make this work on my setup and then contribute documentation here or make a PR for neoformat to include exfmt for Elixir files :-)

[Link to working config](https://github.com/jfornoff/dotfiles/commit/00d25359acb658c7396ac0d7b36b301b0b2d1c25)

**Comment by jfornoff** [comment]
Also, it might be nice to provide a way to install exfmt locally (maybe using `mix archive.install`?), just so you don't have to specify it as a dev dependency on every project, if that sounds good i can look this up as well!

**Comment by lpil** [comment]
I don't want to commit to a way to globally install exfmt yet as I feel we're still on the discovery phase. For the same reason I don't think we're ready to merge the configuration into core Neoformat. I'd like to just document the configuration required to get it working with the mix task for a single user to start :)

**Comment by jfornoff** [comment]
Gotcha, sounds reasonable. I'll open a PR on the docs in the next few days
documenting the process.

**Comment by lpil** [comment]
Thank you :)

**Comment by jfornoff** [comment]
Ready to close this?

**Comment by lpil** [comment]
Oh yes, thanks!
