### ISSUE TITLE
Atom integration

### ISSUE THREAD

**Issue by lpil** [lpil/exfmt#28]
## Dependencies:

- [x] https://github.com/lpil/exfmt/issues/23
- [x] https://github.com/lpil/exfmt/issues/24
- [x] https://github.com/lpil/exfmt/issues/25

**Comment by rgreenjr** [comment]
I'll work on this issue and its three dependencies.

**Comment by lpil** [comment]
Thank you!

**Comment by rgreenjr** [comment]
I just noticed that @binaryseed is close to knocking out most of the CLI dependencies. So I'm going to scrap what I've done and start working on Atom integration.

**Comment by rgreenjr** [comment]
I've got Atom integration working using the new `--stdin` flag. I've called the package **exfmt-atom**, but I'm happy to change it if you prefer something else.

Currently, you have to specify the directory of your local installation of **exfmt**. This is a temporary hack while I investigate the correct way to invoke Elixir dependencies in Atom.

I'll publish the package once we lock on a name.

**Comment by lpil** [comment]
Sounds great! Thank you :)

**Comment by rgreenjr** [comment]
I've published the Atom integration package [exfmt-atom](https://atom.io/packages/exfmt-atom). I'll update the README and add an "Editor Integration" section. It looks like the Visual Studio Code plugin is almost ready as well. I think you can close this issue now.
