### ISSUE TITLE
VS Code integration

### ISSUE THREAD

**Issue by lpil** [lpil/exfmt#29]
## Dependencies:

- [x] https://github.com/lpil/exfmt/issues/23
- [x] https://github.com/lpil/exfmt/issues/24
- [x] https://github.com/lpil/exfmt/issues/25

**Comment by securingsincity** [comment]
Haven't looked at this projecct in a couple weeks but i do have this https://github.com/securingsincity/vscode-exfmt all set up. Let me know how i can help add in any other behaviors

**Comment by lpil** [comment]
Printing of errors to STDERR, input from STDIN and status codes have just been implemented. It'd be great if you could try this plugin with the current master branch :)

Would it be useful to take input from STDIN? Then the user wouldn't need to save the file to disk to format it.

**Comment by securingsincity** [comment]
Ok stderr messages should be working my latest master build and i just pushed out `0.0.2` with support for those messages. I'll work on supporting STDIN so we can format just portions of text or not have to save to format. Great work @lpil

**Comment by lpil** [comment]
Thank you :)

Would you like to add a link to your project in the README?
