### ISSUE TITLE
Cannot format heredocs containing \\

### ISSUE THREAD

**Issue by cloud8421** [lpil/exfmt#43]
Hello 👋 

I'm linking here a file that cannot be formatted by exfmt:

<https://github.com/cloud8421/recipe/blob/b1b3e47c8861970824e976d01694144b89072d73/lib/recipe.ex>

Thanks (and sorry for the vague issue title)

**Comment by lpil** [comment]
Hey Claudio! Thanks for the report :)

**Comment by lpil** [comment]
Pending tests here -> https://github.com/lpil/exfmt/commit/053e9c4848d8061ec540604503fef92ca9f179b9
