### ISSUE TITLE
Place multiline map braces on own lines

### ISSUE THREAD

**Issue by lpil** [lpil/exfmt#44]
```elixir
%{
  foo: 1,
  bar: 2
}
```
See https://github.com/uohzxela/ex_format/issues/29#issuecomment-318616796

**Comment by jfornoff** [comment]
https://github.com/jfornoff/exfmt/commit/ddee5e34efd9e1b6ade34a4ca0b82c514a2019ac
Got a the second brace wrapped into a new line, works for plain map literals.

For variable assignments, you'd want the opening brace to be on the same line as the variable (as José suggested), haven't quite figured that out yet.

Will give it another go later :-)

**Comment by jfornoff** [comment]
Ready to close this?

**Comment by lpil** [comment]
Yes, thanks
