### ISSUE TITLE
[Discussion] Parentheses style

### ISSUE THREAD

**Issue by jfornoff** [lpil/exfmt#48]
Followup issue to #47.

## Parentheses around arguments in anonymous functions
We are currently not adhering to the [guidelines regarding parentheses around fn arguments](https://github.com/lexmag/elixir-style-guide#anonymous-fun-parens), they are recommending against argument parentheses in anonymous functions.

## Parentheses in function calls
The style guide is not explicit about this, but in most of the example snippets, arguments to function calls are always wrapped in parentheses. Currently, the formatter drops parentheses, even for multi-argument functions ([example for this](https://github.com/lpil/exfmt/blob/master/test/exfmt/integration/call_test.exs#L9)).

My personal stance on this would be pro-parentheses, we could also stir up a discussion on the style guide issues if we're not in agreement on what the idiomatic way would be!

**Comment by lpil** [comment]
This is two separate issues.

I think we should remove the argument parens from `fn`s :)

As for function calls people expect certain calls to be called without parens, i.e. `def` and friends. We could just have a list of function names that have no parens, but I don't think this works well as the functions could be redefined, and users will define other functions that shouldn't have parens, i.e. Ecto's `schema`.

The rule currently used is that function calls at the top level or in blocks do not use parens. I like this rule as it seems to result in good output, is conceptually simple and possible to implement.

**Comment by jfornoff** [comment]
Sounds good, I think the consensus on `fn` arguments is already found with an entry in the style guide :-)

For the functions without parens, if we're looking to be 100% compliant to the style guide, we'd have to put the parens on `def` and friends ([specified here](https://github.com/lexmag/elixir-style-guide#fun-parens)).

The point about `schema` is valid, would we maybe distinguish between block and no-block functions there?
Generally, I think that multi-argument functions would benefit from having their arguments in parens, just to have clearer chunks of code.

Maybe to illustrate (borrowed from #13):
```elixir
case Enum.find(state.reporting_periods, fn rp -> StoreReportingPeriod.covers?(rp, now) end) do
  nil ->
    {:ok, rp} = StoreReportingPeriod.start_link(now)
    {rp, %{state | reporting_periods: [rp | state.reporting_periods]}}
  rp ->
    {rp, state}
end
```

```elixir
case Enum.find state.reporting_periods, fn rp -> StoreReportingPeriod.covers? rp, now end  do
  nil ->
    {:ok, rp} = StoreReportingPeriod.start_link(now)
    {rp, %{state | reporting_periods: [rp | state.reporting_periods]}}
  rp ->
    {rp, state}
end
```
IMO, the first chunk is a lot easier to make sense of, what do you think?

**Comment by lpil** [comment]
The first example is the current behaviour as `Enum.find/2` there is not a top level or block level call, it is an argument to `case/2`.

**Comment by jfornoff** [comment]
Oh true, that example doesn't hold then, my bad :-) Still would love to see parens, even on the top level!
Maybe we can get some more input on this from the community?

**Comment by lpil** [comment]
If an alternative method for deciding when to place parens is suggested we can consider it. For now I'm happy with the implementation and behaviour of the existing method so I'm not actively looking for a new one. Very open to change though :)
