### ISSUE TITLE
Mix task not found on install 

### ISSUE THREAD

**Issue by securingsincity** [lpil/exfmt#5]
I'm way too excited about this project, but it doesn't look like the mix task gets assigned upon install. I can see when I run `iex -S mix` I can call `ExFmt` with no issue but `mix exfmt` is not found

**Comment by lpil** [comment]
Hi James!

Thank you for the support :)

The mix task is as of yet unreleased. I could release a new version if you like, but currently there are some known edge cases in which exfmt will output semantically incorrect code. Additionally as this is still very early stages the style used by the formatter is not ideal right now.

Would you like me to release a new version from current master?

Alternatively you could pull the master branch if you just want to try things out :)

Cheers,
Louis

**Comment by securingsincity** [comment]
I just pulled from the master branch and that worked. Thanks!

**Comment by lpil** [comment]
Great! I have one more failing smoke test, but once it's fixed I'll release a new version.

**Comment by securingsincity** [comment]
Sweet I put together a VScode extension based on `exfmt` https://github.com/securingsincity/vscode-exfmt I'm just playing around with it but I'll let you know if I catch any strange behavior

**Comment by lpil** [comment]
That's very cool. I'll do the same for vim soon.
