### ISSUE TITLE
Any Elixir warnings will be inserted into the file via Neoformat

### ISSUE THREAD

**Issue by MainShayne233** [lpil/exfmt#53]
With my Elixir version differing from some of the archives I have installed, I get warnings like:

`warning: the archive nerves_bootstrap requires Elixir "~> 1.4.0" but you are running on v1.5.0`

when compiling and such. 

When using `Neoformat` + `exfmt` and running `:Neoformat`, that warning gets inserted into the file:

```
warning: the archive nerves_bootstrap requires Elixir "~> 1.4.0" but you are running on v1.5.0
defmodule Store.Map do
  use GenServer
  alias Store.ETS
```

**Comment by jfornoff** [comment]
Thanks for reporting, will look into this later today! :-)

**Comment by jfornoff** [comment]
Can reproduce the issue, seems somewhat tricky since the warnings are emitted by `mix` itself, and setting `MIX_QUIET` does not suppress them.

For where the error outputs are apparently coming from:
```
$ MIX_DEBUG=1 mix exfmt maps.ex
** Running mix loadconfig (inside Standupbot.Mixfile)
** Running mix exfmt maps.ex (inside Standupbot.Mixfile)
** Running mix deps.loadpaths (inside Standupbot.Mixfile)
** Running mix deps.precompile (inside Standupbot.Mixfile)
==> exfmt
warning: the dependency :exfmt requires Elixir "~> 1.5" but you are running on v1.4.4
** Running mix compile --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Exfmt.Mixfile)
** Running mix loadpaths --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Exfmt.Mixfile)
** Running mix compile.all --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Exfmt.Mixfile)
** Running mix compile.yecc --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Exfmt.Mixfile)
** Running mix compile.leex --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Exfmt.Mixfile)
** Running mix compile.erlang --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Exfmt.Mixfile)
** Running mix compile.elixir --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Exfmt.Mixfile)
** Running mix compile.xref --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Exfmt.Mixfile)
** Running mix compile.app --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Exfmt.Mixfile)
```

Will try to dig deeper into this later!

**Comment by lpil** [comment]
Are these warnings written to STDOUT or STDERR? Seems we should configure Neoformat to ignore STDERR.

**Comment by jfornoff** [comment]
STDOUT unfortunately :-(

**Comment by lpil** [comment]
@josevalim is there a way to silence these or send to STDERR?

**Comment by josevalim** [comment]
I don't believe we have an option right now. One quick option that comes to mind is for you to insert a separator at the beginning of the file and let the tool use it as getting starting point. I am not sure if Neoformat supports it though. Another option is to provide a way to run the tool without using mix. Maybe via an escript.

**Comment by jfornoff** [comment]
AFAIK Neoformat just uses the whole STDOUT output of the tool that it's calling, so this won't work out of the box probably..

Another interesting perk of running as an escript might be that we'd be able to depend on more cutting-edge Elixir versions without running into version problems with having `exfmt` as a Mix project dependency, is that correct?

**Comment by lpil** [comment]
I think an escript would be the easier path here. I'd like to wait until a little until a few of the issues closed before we make one though.

I think escript use the system installation of Elixir/Erlang. If so we'd need to use something like a release to distribute exfmt with the newer parser before Elixir v1.6. It might just be easier to move the new tokenizer and parser into this repository for the time being.

**Comment by jfornoff** [comment]
Like the idea! How would we handle versioning and installation when releasing an escript?

**Comment by lpil** [comment]
Once Elixir v1.6 is out (or we have moved the parser) we should be ok just recommending something like this:

```
mix escript.install git https://github.com/lpil/exfmt tag v0.4.0 --sha512 SHA_GOES_HERE
```

**Comment by josevalim** [comment]
The escript embeds Elixir. This can even be beneficial because you can distribute the escript with elixir master in it, which has all of the tokenizer/parser changes that you need.

**Comment by lpil** [comment]
Ah, fantastic, I did not know this. Thanks Jose :)
