### ISSUE TITLE
Align closing 'end' of anonymous functions in argument list with top-level call

### ISSUE THREAD

**Issue by jfornoff** [lpil/exfmt#54]
Currently, we are aligning the starting `->` and the `end` tokens of anonymous functions when passing them as arguments.

### Current formatting:
```elixir
test "fn in long function calls" do
  """
  Enum.find([1,2,3,4], fn num -> rem(num, 2) == 0 end)
  """ ~> """
  Enum.find [1, 2, 3, 4],
            fn num ->
              rem(num, 2) == 0
            end
  """

  """
  Logger.debug fn -> "Hey this is a long log message!" end
  """ ~> """
  Logger.debug fn ->
                 "Hey this is a long log message!"
               end
  """
end
```

### Desired formatting
The idiomatic way usually employed ([example in the style guide](https://github.com/lexmag/elixir-style-guide#space-before-anonymous-fun-arrow)) aligns the `end` token with the calling function.

**Comment by lpil** [comment]
Could be a bit of a tricky one. :)
