### ISSUE TITLE
Render parens on qualified zero arity function calls

### ISSUE THREAD

**Issue by lpil** [lpil/exfmt#58]
https://github.com/lexmag/elixir-style-guide#parentheses

```elixir
# Bad
Mix.env

# Good 
Mix.env()
```

Let's only target calls where the left hand side is either an atom or a module alias for now. Other calls will be tricky as they may be accessing a map property rather than a call.

**Comment by rgreenjr** [comment]
I'm happy to start working on this one.

**Comment by lpil** [comment]
Ace, thank you

**Comment by rgreenjr** [comment]
After some investigation, it appears there are four zero arity contexts that need to be differentiated to implement this feature:

1. Zero arity qualified function calls to an alias ([reference](https://github.com/lexmag/elixir-style-guide#zero-arity-parens))

```elixir
# Bad
Mix.env

# Good
Mix.env()
```

2. Zero arity qualified function calls to an atom

```elixir
# Bad
:random.uniform

# Good
:random.uniform()
```

3. Zero arity non-qualified function calls

```elixir
# Bad
pid = self

# Good
pid = self()
```

4. Zero arity types ([reference](https://github.com/lexmag/elixir-style-guide#parens-in-zero-arity-types))

```elixir
# Bad
@spec start_link(module(), term(number), Keyword.t()) :: on_start()


# Good
@spec start_link(module, term(number), Keyword.t) :: on_start
```

I've got 1, 2, and 4 working. I'm going to try knock out 3 this weekend.

**Comment by rgreenjr** [comment]
Quick question, what is the correct style for ```Map.new.key```? Do you know if it should be formatted as ```Map.new().key```? 

I couldn't find an example that covers this scenario in the Elixir Style Guide.

**Comment by rgreenjr** [comment]
Another question along the same line. There's a test for "aliases with variable part" which contains ```One.x.Three```. I'm unfamiliar with variable aliases. Should this too be formatted as ```One.x().Three```?

Thanks.

**Comment by lpil** [comment]
For `Map.new.key` I'm unsure. We should open an issue in the style guide to ask. For now we can do whatever is easiest and fix it later when we have more knowledge.

For an alias with a variable section we should avoid using parens, at least for now.

**Comment by lpil** [comment]
Thank you! :D

**Comment by rgreenjr** [comment]
Great, thanks for the quick reply. I'll open an issue in the style guide to ask about ```Map.new().key```. Right now it's easiest to add the parenthesis. I'll also see if I can avoid adding a parenthesis to ```One.x.Three```.

**Comment by rgreenjr** [comment]
After more investigation, I'm not sure how to avoid adding a parenthesis to an alias with a variable section. There doesn't appear to be anything in the context that allows me to differentiate ```Mix.env``` from ```One.x.Three```, so it gets formatted as ```One.x().Three```. 

I'll issue a pull request so you can see what I've done. You may see something I missed.

**Comment by rgreenjr** [comment]
I posted to Elixir Style asking about parenthesis on chained functions: ```Map.new().key```. There was a consensus that parenthesis should always be used on zero arity functions, even when chaining.
