### ISSUE TITLE
@moduledoc multi-line formatting

### ISSUE THREAD

**Issue by dmix** [lpil/exfmt#61]
The autogenerated context (aka model) files in Phoenix 1.3 use a multi-line @moduledoc for each function:

``` Elixir
  @doc """
  Returns the list of roles.

  ## Examples

      iex> list_roles()
      [%Role{}, ...]

  """
  def list_roles do
    Repo.all(Role)
  end
```

Which gets formatted like so:

```Elixir
  @doc "Returns the list of roles.\n\n## Examples\n\n    iex> list_roles()\n    [%Role{}, ...]\n\n"
  def list_roles do
    Repo.all Role
  end
```

These @moduledocs are all over my application, 20 or so in just the one file I'm working on. So this is preventing me from using `exfmt` sadly.

Is there a plan to have a config file to disable certain formatting ala [`.credo.exs`](https://github.com/rrrene/credo/blob/master/.credo.exs)?

**Comment by whatyouhide** [comment]
I believe that the problem is just that exfmt has not been updated to use the changes in https://github.com/elixir-lang/elixir/pull/6372 which make it possible to tell heredocs apart and hence to format them as `"""` if `"""` was used (that is, no need for config).

**Comment by lpil** [comment]
Some (though not all) heredoc syntax is preserved on the master branch. More will come next week, this week I'm spending my free time preparing for www.elixir.london :)

See the changelog for more info https://github.com/lpil/exfmt/blob/master/CHANGELOG.md

**Comment by dmix** [comment]
Thanks for the quick responses.

Just a quick update, testing the latest `exfmt` on master it still seems to convert the heredoc lines to a single line with "\n\n", so this is still an ongoing issue. Looking forward to the upcoming updates.

**Comment by lpil** [comment]
Could you provide a code example please? :)

**Comment by dmix** [comment]
The code example I included in the original issue above (the @doc above `list_roles`) is still outputting the same way using the latest code on master...

I can provide more examples but it's pretty much all the same, the multi-line string between `"""` get's flattened into a single line with \n\n instead of line breaks.

**Comment by lpil** [comment]
How are you adding exfmt to your project? The are test cases that state this should not happen, so I'm confused. Does the heredoc have interpolation?

**Comment by kokjinsam** [comment]
I can verify that this is still an issue. I'm using `vscode-exfmt` with `exfmt` v0.4.0.

**Comment by lpil** [comment]
Heredoc rendering was implemented after v0.4.0 I'm afraid.

**Comment by kokjinsam** [comment]
:thinking: Hmm. So I'm using exfmt directly from github and it doesn't seem like the issue is fixed.

**Comment by lpil** [comment]
Could you give an example, the exfmt version SHA, the Elixir version SHA and the method of installation & use please?

**Comment by kokjinsam** [comment]
I added this line:

```
{:exfmt, [github: "lpil/exfmt", only: :dev, runtime: false]}
```

to my deps in Mix file. Then I ran `mix deps.get` and `mix deps.compile`. At the top of the stack, I saw `warning: the dependency :exfmt requires Elixir "~> 1.6-dev" but you are running on v1.5.1`. I used `vscode-exfmt` for code formatting.

This:

```
@moduledoc """
Test
Test
"""
```
became this:
```
@moduledoc "Test\nTest\n"
```

I'm not sure if this is the version SHA you're looking for:

```
"exfmt": {:git, "https://github.com/lpil/exfmt.git", "c4b6abe01b8579e07480c32784c12ecf26f3e746", []}
```

**Comment by lpil** [comment]
Elixir 1.5 isn't supported I'm afraid, exfmt uses new compiler features coming in 1.6 in order detect heredocs

**Comment by kokjinsam** [comment]
Ah I see. Thank you for your response! I will check it out again when 1.6 is released. Great work on this btw!

**Comment by lpil** [comment]
Thank you :)
