### ISSUE TITLE
Global install via an escript

### ISSUE THREAD

**Issue by justgage** [lpil/exfmt#71]
II think it would be great to have a way to install this globally as an executable or something like that. This way it doesn't have to be included in the project I'm working on.

**Comment by lpil** [comment]
Hello! This is a goal, just need to do a little more work on the output style first :)

**Comment by justgage** [comment]
Totally, I just thought it would be nice go have a ticket to track that @lpil. By the way I ❤️ this soooo much. I've been using prettier as of late and I've sorely missed it in Elixir land.

**Comment by lpil** [comment]
I know the feeling! Thank you for the support :)

**Comment by jfornoff** [comment]
@lpil I could try building an Escript with 1.6.0-dev packaged, since people increasingly ask for it. Would you be open to that?

**Comment by lpil** [comment]
I'd like to support Linux, OSX and Windows. How would we build for each of these platforms?

Where would we publish the binaries for downloading? :)

**Comment by jfornoff** [comment]
I got a Linux and a Windows box to test on, if you got a OSX box, we're probably fine.
Maybe we could use Github releases and publish the Escripts automatically on new tags through CI eventually.

Got a working version BTW, want me to just drop it somewhere and try it out?
Executes totally fine on my Linux box!

**Comment by lpil** [comment]
I'm only a Linux user I'm afraid. Could you make a PR to share the code? :)

**Comment by jfornoff** [comment]
Yes, I'll shoot you a PR in a second.

Testing the Escript on my Windows box atm, apparently there's some requirement posed on the Erlang installation on the system, i.e. there is `escript` the command available, which seems to be distributed with Erlang itself. My Windows Erlang installation (through `chocolatey`) does not seem to include it, so we might have to keep an eye on that.
