### ISSUE TITLE
CoC is missing a contact to report stuff

### ISSUE THREAD

**Issue by Tuxified** [lpil/exfmt#82]
While reading through the [CoC](https://github.com/lpil/exfmt/blob/master/CODE_OF_CONDUCT.md) I noticed the email for reporting misbehaviour was missing, it's now `[INSERT EMAIL ADDRESS]`. I feel it should either mention a person/email to which people can report or change the description about enforcement.

**Comment by lpil** [comment]
Oops, thank you.
