### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by savoisn** [lpil/exfmt#83]
Just got it working
Thanks an awesome feature for the language thanks a lot :)

I've been missing a few installation instruction
Would you like a PR with something like the following :

## Installation : 

Add exfmt to your project dependencies:

```elixir
# mix.exs (Elixir 1.5)
def deps do
  [{:exfmt, "~> 0.4.0", only: :dev, runtime: false}]  
end
```
update your dependencies with : 
```
mix deps.get
```
all is ready to run :)

**Comment by kitlangton** [comment]
Thanks @lpil for making this! And thanks @savoisn for letting me know how to install it! :^D

**Comment by lpil** [comment]
Hiya. Thanks for the contribution but these instructions are incorrect as Elixir v1.5 isn't supported.
