### ISSUE TITLE
Allow for single line function definitions

### ISSUE THREAD

**Issue by jfornoff** [lpil/exfmt#85]
```elixir
def even?(1), do: false
def even?(2), do: true
```
is reformatted to

```elixir
def even?(1) do
  false
end

def even?(2) do
  true
end
```

So it does not seem like we're formatting to single-line function definitions yet, when it would probably make sense.

**Comment by lpil** [comment]
In order to support this syntax we would need a rule for deciding when to use which syntax. What might we use here?
