### ISSUE TITLE
Future of ExFmt

### ISSUE THREAD

**Issue by sean-clayton** [lpil/exfmt#86]
Since [Elixir 1.6 will introduce a formatter](https://github.com/rrrene/credo/pull/443), what will happen with this project?

**Comment by OvermindDL1** [comment]
Better to give the direct link, I'm pretty sure it's this:  https://github.com/whatyouhide/code_formatter
Maybe better to talk to them, they started not long ago.

**Comment by lpil** [comment]
When `code_formatter` is released this project will be redundant. Until then 🤷
