### ISSUE TITLE
Request: Configuration option for parentheses in function calls

### ISSUE THREAD

**Issue by udfalkso** [lpil/exfmt#9]
I'm personally a big fan of parenthesis to identify function calls and make my code more readable.  

exmt takes this:
```
persist_adjustments(disagree_rater_ids, [review_karma: -5])
```
and turns it into this:
```
persist_adjustments disagree_rater_ids, review_karma: -5
```

I think that the former is much more readable and I would like to keep the parenthesis around (as well as the brackets around the keyword list, but we can probably discuss that issue separately)

I realize not everyone may share this opinion, but perhaps exfmt could have a few configurable options around issues like this?  Much like prettier lets you choose semicolons or not, etc.  

Thanks!

**Comment by lpil** [comment]
exfmt will not support any configuration. The current style is not final (or even close). The current goal is to make the formatter correct, them the work on the style will start :)

**Comment by udfalkso** [comment]
That's a shame.  I won't use it in that case myself.  Otherwise it seems like a great project.  Best of luck!

**Comment by lpil** [comment]
Thanks!

**Comment by lpil** [comment]
Just to clarify, we may use the style you suggested, but currently it's too early. First iron out the bugs, then later make it pretty :)
