### ISSUE TITLE
 (FunctionClauseError) no function clause matching in Access.get/3   

### ISSUE THREAD

**Issue by altanozlu** [lpil/exfmt#92]
`** (FunctionClauseError) no function clause matching in Access.get/3    
    
    The following arguments were given to Access.get/3:
    
        # 1
        {80, {5, 8}, nil}
    
        # 2
        :line
    
        # 3
        nil
    
    Attempted function clauses (showing 5 out of 5):
    
        def get(-%module{} = container-, +key+, +default+)
        def get(+map+, +key+, +default+) when -is_map(map)-
        def get(+list+, +key+, +default+) when -is_list(list)- and +is_atom(key)+
        def get(+list+, +key+, +_default+) when -is_list(list)-
        def get(-nil-, +_key+, +default+)
    
    (elixir) lib/access.ex:306: Access.get/3
    lib/exfmt/comment.ex:97: Exfmt.Comment.line/1
    lib/exfmt/comment.ex:84: anonymous fn/2 in Exfmt.Comment.merge_node/2
    (elixir) lib/enum.ex:3169: Enum.split_while_list/3
    lib/exfmt/comment.ex:85: Exfmt.Comment.merge_node/2
    (elixir) lib/macro.ex:238: Macro.traverse/4
    lib/exfmt/comment.ex:68: Exfmt.Comment.merge/2
    lib/exfmt.ex:131: Exfmt.do_format/3`

Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

IEx 1.6.0-dev (b6a5589) (compiled with OTP 20)

**Comment by joaothallis** [comment]
I got the same error
