### ISSUE TITLE
Stable release ETA

### ISSUE THREAD

**Issue by soullivaneuh** [lpil/exfmt#93]
I'm interested to implement your tool under my [FlintCI](flintci.io) project.

Do you have any ETA for the stable release? Is the output format stable enough or not at all?

Thanks.

**Comment by lpil** [comment]
Hi, thanks for the message! When Elixir 1.6 lands (hopefully within a few weeks) this project will be formally deprecated as there will be an official formatter. :)

**Comment by OvermindDL1** [comment]
Except the official formatter is really *really* broken on certain code constructs that they refuse to fix.  I'd still really like to see this one developed to be a configurable one.  :-)

**Comment by lpil** [comment]
Could you give examples?

Zero configuration is the number 1 project goal here I'm afraid!

**Comment by OvermindDL1** [comment]
Many that have been stated on the forum, but in my case I've had 2 things that it just turned to absolute horror...  ^.^;

1. The first was a large list of precalculated numbers arranged in specific rows based on mathematical properties, that all got put down to a list of numbers, with one-number-per-line, turning 16 lines of well readable math related code into 256 lines of unreadable horror.

2. Binary matching/building.  Like say you are parsing, oh, a TCP packet (or in my case various binary specs), it will end up flattening that all out to one variable per line, making 4 very readable lines that practically read like the spec (in my case) become 38 lines of unreadable horror.

In addition to various other wtf'y things that they chose.  Not everyone likes their formatter.  Elixir is primarily geared toward simple web dev's, not people that tend to do (oh I hate using this phrase, so so much...) real backend work, and the formatter is geared to that use-case.  >.>

**Comment by lpil** [comment]
I don't see any problem with that formatting. This tool is intended to prevent this kind of bike shedding, competing with the official formatter and allowing configuration would both be counter-productive.

**Comment by OvermindDL1** [comment]
> I don't see any problem with that formatting. This tool is intended to prevent this kind of bike shedding, competing with the official formatter and allowing configuration would both be counter-productive.

I don't find these things as bikeshedding however, it is not just negatively but *significantly* negatively affecting my ability to both read and write the code related to those sections, bad enough that I have the formatter banned in such projects as manually attempting to reformat it back would be a non-insignificant amount of work just to be able to understand the code and work on it.

**Comment by lpil** [comment]
I would recommend having this discussion over in the active project :)

**Comment by OvermindDL1** [comment]
> I would recommend having this discussion over in the active project :)

Ooo?  Where'd that be?  :-)

**Comment by lpil** [comment]
I'd go for the official formatter, I don't think any of the others are active any more.

**Comment by OvermindDL1** [comment]
> I'd go for the official formatter, I don't think any of the others are active any more.

Already been discussed with it, the issue is that such formatting is context specific and cannot be determined just by looking at the AST, and as the formatter will not be configurable to be able to disable it for blocks then it will likely forever break such readability semantics, so... yeah, it's not useful...  ^.^;
